# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"scale_minmax": "00_core.ipynb",
         "save_encoder": "00_core.ipynb",
         "load_encoder": "00_core.ipynb",
         "sounds_source": "01_data.ipynb",
         "get_spec": "01_data.ipynb",
         "get_duration": "01_data.ipynb"}

modules = ["core.py",
           "data.py"]

doc_url = "https://lgvaz.github.io/animal_sounds/"

git_url = "https://github.com/lgvaz/animal_sounds/tree/master/"

def custom_doc_links(name): return None
